Repository tpfkalrrltk/KH12-Final-4Jo, pull requests merged in 2023-11, with the labels that each got.

#33 moim-mapper 생성 등
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
Labels: enhancement

#36 Yeji
  EveryFit/src/main/java/com/kh/EveryFit/controller/ProductController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/ProductDaoImpl.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/product-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/product/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/product/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/product/update.jsp
Labels: enhancement

#38 Junhee
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueRestController.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/league-mapper.xml
Labels: enhancement

#35 모임게시판 CRUD 구현
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/moimBoardRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/moimBoardRestController.java
  EveryFit/src/main/resources/mybatis/moimBoard-mapper.xml
Labels: enhancement

#37 회원 swagger
  EveryFit/src/main/java/com/kh/EveryFit/configuration/RestApiconfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MemberDto.java
  EveryFit/src/main/java/com/kh/EveryFit/error/ExceptionControllerAdvice.java
  EveryFit/src/main/java/com/kh/EveryFit/error/NoTargetException.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MemberRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/MemberRestController.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/member-mapper.xml
Labels: enhancement

#40 kakaopay를 위한 준비(vo,service)구성
  EveryFit/src/main/java/com/kh/EveryFit/configuration/KakaoPayConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/configuration/KakaoPayProperties.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/service/KakaoPayService.java
  EveryFit/src/main/java/com/kh/EveryFit/service/KakaoPayServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/KakaoPayAmountVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/KakaoPayApproveRequestVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/KakaoPayApproveResponseVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/KakaoPayCardInfoVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/KakaoPayReadyRequestVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/KakaoPayReadyResponseVO.java
Labels: enhancement

#41 moimDao / moimDaoImpl 생성
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/ChatDto.java
  EveryFit/src/main/resources/mybatis/chat-mapper.xml
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
Labels: enhancement

#42 kakaopay 단건 결제 payment db에저장없이
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/ProductDao.java
  EveryFit/src/main/java/com/kh/EveryFit/service/KakaoPayServiceImpl.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/successResult.jsp
Labels: enhancement

#43 회원가입,로그인,홈
  EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/EventDto.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LocationDto.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MemberDto.java
  EveryFit/src/main/resources/mybatis/member-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/joinFinish.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
Labels: enhancement

#44 헤더,풋터 설정 및 홈페이지 연동
  EveryFit/src/main/resources/static/css/EveryFit-layout.css
  EveryFit/src/main/resources/static/css/test.css
  EveryFit/src/main/resources/static/images/logo.png
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: good first issue

#45 회원가입, 마이페이
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/resources/mybatis/member-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: documentation

#46 헤더링크 수정, 풋터 폰트 수정
  EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: enhancement

#47 파일 업로드 구현 중
  EveryFit/src/main/java/com/kh/EveryFit/configuration/FileUploadProperties.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AttachDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AttachDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/AttachDto.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/AttachRestController.java
  EveryFit/src/main/resources/mybatis/attach-mapper.xml
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
Labels: enhancement

#48 임시 수정
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: documentation

#49 리그 관련 기본 crud restAPI 구현
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueApplicationDto.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueDto.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueMatchDto.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueTeamDto.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueTeamRoasterDto.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueApplicationRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueMatchRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueTeamRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueTeamRoasterRestController.java
  EveryFit/src/main/resources/mybatis/league-mapper.xml
Labels: documentation

#51 게시판 CRUD 오류 수정
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/FreeBoardRestController.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/faq-mapper.xml
  EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml
  EveryFit/src/main/resources/mybatis/moimBoard-mapper.xml
Labels: enhancement

#52 마이페이지,회원가입 디자인, 회원정보수정 진행
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/resources/static/images/profile.jpg
  EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/modal.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: documentation

#54 리그 정렬 수정
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueListDto.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/LeagueListVO.java
  EveryFit/src/main/resources/mybatis/league-mapper.xml
Labels: enhancement

#57 스케줄러잠깐삭제
  EveryFit/src/main/java/com/kh/EveryFit/dto/PeriodPaymentDto.java
  EveryFit/src/main/java/com/kh/EveryFit/service/KakaoPayServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/service/PaymentScheduler.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/PaymentListAllVO.java
  EveryFit/src/main/resources/mybatis/payment-mapper.xml
Labels: invalid

#56 자유게시판 수정
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/FreeBoardDto.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/FreeBoardRestController.java
  EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml
Labels: enhancement

#58 restApi 잡것용
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/InfoRestController.java
Labels: enhancement

#59 개인정보 수정 구현중
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: documentation

#60 정기결제 완료 후 정기결제 테이블에 정보 저장 완료
  EveryFit/src/main/java/com/kh/EveryFit/dao/PaymentDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/PaymentDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/service/PaymentScheduler.java
  EveryFit/src/main/resources/mybatis/payment-mapper.xml
  EveryFit/src/main/resources/static/images/memberCard.PNG
  EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: documentation

#61 Junhee
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/LocationRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/InfoRestController.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/league-mapper.xml
  EveryFit/src/main/resources/mybatis/member-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueList.jsp
Labels: enhancement

#63 정모 등록 및 목록조회 구현 중
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/JungmoDto.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/AttachRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/resources/mybatis/attach-mapper.xml
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/jungmoCreate.jsp
Labels: enhancement

#64 풋터 수정
  EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp
Labels: enhancement

#65 헤더 디자인 수정
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: enhancement

#66 이메일 인증, 비밀번호 찾기, 비밀번호 확인 구현중
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/CertDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/CertDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/CertDto.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MemberBlockDto.java
  EveryFit/src/main/java/com/kh/EveryFit/error/AuthorityException.java
  EveryFit/src/main/resources/mybatis/cert-mapper.xml
  EveryFit/src/main/resources/mybatis/member-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/exit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
  EveryFit/src/test/java/com/kh/EveryFit/Test01.java
Labels: documentation

#67 Soeun정모 정보 수정 / 모임 정보 수정 구현 중
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/JungmoDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/JungmoDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/JungmoMemberDto.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/AttachRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/JungmoListByMoimNoVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/JungmoListVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/JungmoMemberListVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/JungmoWithMembersVO.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/jungmoCreate.jsp
Labels: enhancement

#68 헤더 로그인 로그아웃 표시
  EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: documentation

#70 단건결제 목록과 취소 처리 구현
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/PaymentDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/PaymentDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/service/KakaoPayService.java
  EveryFit/src/main/java/com/kh/EveryFit/service/KakaoPayServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/KakaoPayCancelRequestVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/KakaoPayCancelResponseVO.java
  EveryFit/src/main/resources/mybatis/payment-mapper.xml
  EveryFit/src/main/resources/static/images/moinCard.PNG
  EveryFit/src/main/webapp/WEB-INF/views/pay/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
  EveryFit/src/main/webapp/WEB-INF/views/product/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/product/update.jsp
Labels: enhancement

#71 디자인을 제외한 자유게시판
  EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: good first issue

#72 Junhee
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueEdit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueInsert.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: enhancement

#73 게시판 디자인 일부 수정(풋터 변경 예정)
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: enhancement

#74 리그접수일정 괜히 리스트에서 비동기로 하려다가 벽느낌, 부트스트랩 버전 수정
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: enhancement

#75 faq게시판 기능 구현, 헤더 검색 버튼 색상 변경
  EveryFit/src/main/java/com/kh/EveryFit/controller/FaqController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDaoImpl.java
  EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: documentation, enhancement

#77 faq 게시판 CRUD 오류 수정
  EveryFit/src/main/java/com/kh/EveryFit/controller/FaqController.java
  EveryFit/src/main/resources/mybatis/faq-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
Labels: duplicate

#78 카카오페이 단건/정기 결제에 대한 취소/비활성화 버튼 생성
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/PaymentDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/PaymentDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/service/KakaoPayService.java
  EveryFit/src/main/java/com/kh/EveryFit/service/KakaoPayServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/KakaoPayCancelRequestInPeriodVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/KakaoPayCancelResponseInPeriodVO.java
  EveryFit/src/main/resources/mybatis/payment-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/pay/list.jsp
Labels: enhancement, good first issue

#79 자유게시판,FAQ 게시판 수정, 등록 디자인 추가
  EveryFit/src/main/java/com/kh/EveryFit/controller/FaqController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java
  EveryFit/src/main/resources/mybatis/faq-mapper.xml
  EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: documentation

#81 이메일 인증,타이머
  EveryFit/pom.xml
  EveryFit/src/main/java/com/kh/EveryFit/configuration/EmailConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/configuration/EmailProperties.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MemberRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/CertRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/MemberRestController.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/cert-mapper.xml
  EveryFit/src/main/resources/templates/email.html
  EveryFit/src/main/webapp/WEB-INF/views/member/findPw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPwFinish.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: documentation

#82 풋터 위치 하단 포지션 수정
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: duplicate

#83 웹소켓 채팅 구현 중
  EveryFit/pom.xml
  EveryFit/src/main/java/com/kh/EveryFit/configuration/WebsocketServerConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/WebsocketViewController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/ChatDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/ChatDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/JungmoDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/JungmoDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/ChatDto.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MoimMemberDto.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/ChatRoomVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/ClientVO.java
  EveryFit/src/main/java/com/kh/EveryFit/websocket/DefaultWebsocketServer.java
  EveryFit/src/main/resources/mybatis/chat-mapper.xml
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/resources/static/images/user.png
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/chatList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
Labels: enhancement

#84 자유게시판 검색기능 구현중
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/BoardVO.java
  EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: enhancement

#85 자유게시판, FAQ 페이징, 검색기능 구현
  EveryFit/pom.xml
  EveryFit/src/main/java/com/kh/EveryFit/controller/FaqController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/BoardVO.java
  EveryFit/src/main/resources/mybatis/faq-mapper.xml
  EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
Labels: enhancement

#86 Junhee
  EveryFit/src/main/java/com/kh/EveryFit/component/TimeFormatter.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueApplicationDto.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/LeagueRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/CheckMoimListVO.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/league-mapper.xml
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueList.jsp
Labels: enhancement

#87 회원가입 이메일인증 구현중
  EveryFit/pom.xml
  EveryFit/src/main/java/com/kh/EveryFit/configuration/EncryptConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/CertDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/CertDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/CertRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/service/EmailService.java
  EveryFit/src/main/java/com/kh/EveryFit/service/EmailServiceImpl.java
  EveryFit/src/main/resources/templates/celebration.html
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
Labels: documentation

#88 자유 게시판 댓글 구현중
  EveryFit/src/main/java/com/kh/EveryFit/dto/FreeBoardReplyDto.java
  EveryFit/src/main/resources/mybatis/freeBoardReply-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
Labels: enhancement

#89 이메일 인증번호 받기 재수정
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
Labels: enhancement

#90 리그 참여 가능한 모임 처리/ 헤더에 가려지는거 수정
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueTeamCheckDto.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamInsert.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: enhancement

#91 회원 가입시 이메일 인증 연동 기능 구현 오류 해결
  EveryFit/src/main/java/com/kh/EveryFit/dao/CertDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/CertRestController.java
  EveryFit/src/main/resources/mybatis/freeBoardReply-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: bug, enhancement

#93 헤더 풋터 위치 오류 수정 및 자유게시판 댓글 컨트롤러 작업중
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardReplyDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardReplyDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/FreeBoardReplyRestController.java
  EveryFit/src/main/resources/mybatis/freeBoardReply-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: enhancement

#94 회원가입페이지
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/CertRestController.java
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
Labels: enhancement

#95 댓글 페이지 구현중, 회원 이메일 확인 오류 해결, 헤더 회원 마이페이지 추가
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardReplyDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardReplyDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/FreeBoardReplyRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/CertRestController.java
  EveryFit/src/main/resources/mybatis/freeBoardReply-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: enhancement

#96 자유 게시판 파일 전송을 위한 사전작업, 헤더.jsp active 클래스 삭제
  EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java
  EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml
  EveryFit/src/main/resources/static/images/no-image.png
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation

#97 Junhee
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueDto.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/LeagueRestController.java
  EveryFit/src/main/resources/mybatis/league-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueEdit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueInsert.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamInsert.jsp
Labels: enhancement

#98 헤더 현재시각 표시 기능 구현, 게시판 버튼 스크롤시 회전기능 추가
  EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: enhancement

#99 웹소켓 채팅방 회원목록 구현 중
  EveryFit/src/main/java/com/kh/EveryFit/configuration/WebsocketServerConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/WebsocketViewController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/ChatDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/ChatDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelService.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/ChatRoomVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/ClientVO.java
  EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java
  EveryFit/src/main/java/com/kh/EveryFit/websocket/DefaultWebsocketServer.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/chat-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
Labels: enhancement

#100 자유게시판 댓글 기능 구현 완료 (디자인X)
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardReplyDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardReplyDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/FreeBoardDto.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/FreeBoardReplyDto.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/FreeBoardReplyRestController.java
  EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml
  EveryFit/src/main/resources/mybatis/freeBoardReply-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
Labels: enhancement, good first issue

#101 리그 상세페이지 - 순위 테이블, 리그팀 승인
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueTeamDto.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/LeagueRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/LeagueTeamRankListVO.java
  EveryFit/src/main/resources/mybatis/league-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamDetail.jsp
Labels: enhancement

#103 Seungseok2
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MemberDto.java
  EveryFit/src/main/resources/mybatis/secure-member-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/joinFinish.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
Labels: documentation

#105 회원가입이메일인증,로그인,회원탈퇴,개인정보수정
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MemberDto.java
  EveryFit/src/main/resources/mybatis/secure-member-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/joinFinish.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
Labels: documentation

#106 모임게시판에 카테고리 선택하여 선택항목만 리스트에 나오게 구현
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimBoradController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/service/KakaoPayService.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/moimBoard-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/boardTable.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/list.jsp
Labels: enhancement

#107 자유 게시판 사진 등록 기능 구현
  EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/FreeBoardDto.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/FreeBoardAttachRestController.java
  EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
Labels: documentation, enhancement, good first issue

#108 FAQ 게시판 사진 파일 전송 기능 구현
  EveryFit/src/main/java/com/kh/EveryFit/controller/FaqController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/FAQAttachRestController.java
  EveryFit/src/main/resources/mybatis/faq-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp
Labels: documentation, enhancement, good first issue

#109 회원권 구매 후 member_moim_count (3->10) 되도록 업데이트
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/resources/mybatis/member-mapper.xml
Labels: enhancement

#110 모임 멤버 상태 차단/승인 변경 구현, 모임/정모 정보 수정 구현 중
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/MoimMemberStatusVO.java
  EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java
  EveryFit/src/main/resources/mybatis/chat-mapper.xml
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/jungmoCreate.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/chatList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
Labels: enhancement

#111 리그 참여팀 승인
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueTeamDto.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/LeagueRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueMatchRestController.java
  EveryFit/src/main/resources/mybatis/league-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueEdit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueInsert.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamInsert.jsp
Labels: enhancement

#113 자유게시판, FAQ 글 작성,수정 디자인 변경
  EveryFit/src/main/webapp/WEB-INF/views/faq/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/edit.jsp
Labels: duplicate

#115 모임 정보 변경 구현
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/moimBoardRestController.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
Labels: enhancement

#114 리그경기 등록 준비 - 화면에 어케 보여줄지 고민중
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/moimBoardRestController.java
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatch.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatchInsert.jsp
Labels: enhancement

#117 관리자 회원 검색기능 구현중
  EveryFit/src/main/webapp/WEB-INF/views/admin/memberList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/admin/mypage.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
Labels: documentation

#118 로그인,회원가입,이메일인증,회원정보변경,회원탈퇴
  EveryFit/src/main/java/com/kh/EveryFit/dto/MemberDto.java
  EveryFit/src/main/java/com/kh/EveryFit/service/MemberService.java
  EveryFit/src/main/java/com/kh/EveryFit/service/MemberServiceImpl.java
  EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPwFinish.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: enhancement

#119 결제페이지에 모임번호/모임 이름 불러와서 정기결제 페이지로 넘기기
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/PeriodPaymentDto.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/KakaoPayReadyRequestVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/MoimTitleForPaymentVO.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/resources/mybatis/payment-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
Labels: enhancement

#120 관리자의 회원 상세 검색 기능 구현
  EveryFit/src/main/java/com/kh/EveryFit/configuration/EmptyStringControllerAdvice.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/AdminMemberSearchVO.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/admin/memberList.jsp
Labels: documentation, enhancement, good first issue

#121 Junhee
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueMatchDto.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueMatchRestController.java
  EveryFit/src/main/resources/mybatis/league-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatch.jsp
Labels: enhancement

#122 관리자 모임 검색 구현중 임시저장
  EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/AdminMoimSearchVO.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/admin/moimList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation, enhancement

#124 관리자 모임검색 준비중
  EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/AdminMoimSearchVO.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/admin/moimList.jsp
Labels: documentation, duplicate, enhancement

#125 오류 수정 및 정모 입력/수정 모달창으로 구현 중
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
Labels: duplicate, enhancement

#126 관리자의 정모 목록 조회 및 상세 검색기능 구현
  EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/AdminJungmoSearchVO.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/admin/jungmoList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/admin/moimList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation

#127 정모 등록 수정 등 모달로 구현
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/JungmoDetailVO.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
Labels: duplicate, enhancement

#129 결제시 업데이트 되어야 하는 항목들 수정
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/PaymentListAllVO.java
  EveryFit/src/main/resources/mybatis/member-mapper.xml
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/resources/mybatis/payment-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
Labels: enhancement

#131 메인 페이지 목록 종류 추가
  EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/resources/static/images/swiper1.jpg
  EveryFit/src/main/resources/static/images/swiper2.jpg
  EveryFit/src/main/resources/static/images/swiper3.jpg
  EveryFit/src/main/resources/static/images/swiper4.jpg
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
Labels: documentation, enhancement

#132 회원 프로필 업로드구현중
  EveryFit/src/main/java/com/kh/EveryFit/configuration/FileUploadProperties.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MemberRestController.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/attach-mapper.xml
  EveryFit/src/main/resources/mybatis/member-mapper.xml
  EveryFit/src/main/resources/static/images/profile.png
  EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: documentation

#133 웹소켓 회원목록 전송 구현
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AttachDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MoimMemberDto.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/ClientVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/MoimMemberStatusVO.java
  EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
Labels: duplicate, enhancement

#134 메인페이지 디자인 변경 및 모임 인원 보기 기능 추가
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: documentation, enhancement

#135 메인페이지 모임 인원수 손보는중
  EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/HomeRestController.java
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
Labels: documentation, enhancement

#136 Junhee
  EveryFit/src/main/java/com/kh/EveryFit/component/TimeFormatter.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AttachDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AttachDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/service/LeagueScheduler.java
  EveryFit/src/main/resources/mybatis/attach-mapper.xml
  EveryFit/src/main/resources/mybatis/league-mapper.xml
  EveryFit/src/main/resources/static/css/jquery.datetimepicker.min.css
  EveryFit/src/main/resources/static/js/jquery.datetimepicker.full.min.js
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueInsert.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatch.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: enhancement

#137 웹소켓 서버 채팅 구현 중
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/ChatDto.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelService.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/ChatRoomVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/ClientVO.java
  EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java
  EveryFit/src/main/resources/mybatis/chat-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
Labels: duplicate, enhancement

#138 kakaopay결제를 위한 페이지
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/PeriodPaymentDto.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/pay/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/successResult.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation

#139 신고 목록 조회 기능 추가
  EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/ReportDto.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/AdminReportSearchVO.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/resources/mybatis/attach-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/admin/reportList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation, duplicate, enhancement

#140 프로필 업로드 완료
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: documentation

#141 메인페이지 모임 현재인원 출력기능 추가
  EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/AdminMoimMemberCountVO.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
Labels: enhancement

#142 모임 게시판 댓글 구현을 위한 준비
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimBoradController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardReplyDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardReplyDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MoimBoardReplyDto.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimBoardReplyRestController.java
  EveryFit/src/main/resources/mybatis/MoimBoardReply-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/list.jsp
Labels: documentation, enhancement

#144 모임게시판 댓글 구현
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/detail.jsp
Labels: documentation, enhancement

#143 Junhee
  EveryFit/src/main/java/com/kh/EveryFit/component/DateFormatUtils.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/LeagueMatchDto.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/LeagueMatchListVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/LeagueTeamRankListVO.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/attach-mapper.xml
  EveryFit/src/main/resources/mybatis/league-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatch.jsp
Labels: enhancement

#146 모임 가입 및 모임 상세페이지 디자인 구현 중
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelService.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/ChatMemberVO.java
  EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java
  EveryFit/src/main/resources/mybatis/chat-mapper.xml
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
Labels: duplicate, enhancement

#147 간단한 오류 수정(jsp에서 팀리스트 안나오던거)
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatch.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: enhancement

#148 실례가 되지 않는다면 풀 한번 받고 리그 들어와주세요
  EveryFit/src/main/java/com/kh/EveryFit/component/LeagueMatchMaker.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/LeagueRestController.java
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueInsert.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatch.jsp
Labels: enhancement

#149 비밀번호변경 구현중
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/CertRestController.java
  EveryFit/src/main/resources/mybatis/member-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/changePw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/memberChangePw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: documentation

#150 회원의 모임 가입 구현
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
Labels: enhancement

#151 오류 수정
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
Labels: duplicate

#153 Junhee
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/LeagueRestController.java
  EveryFit/src/main/resources/mybatis/league-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatch.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: enhancement

#154 모든 게시판 게시글 레이아웃 수정 및 시간 기능 추가
  EveryFit/src/main/java/com/kh/EveryFit/controller/FaqController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimBoradController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FaqDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/FreeBoardImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/FaqDto.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/FreeBoardDto.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MoimBoardDto.java
  EveryFit/src/main/resources/mybatis/faq-mapper.xml
  EveryFit/src/main/resources/mybatis/freeBoard-mapper.xml
  EveryFit/src/main/resources/mybatis/moimBoard-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/list.jsp
Labels: documentation

#155 모임 등록 및 상세페이지 디자인 수정 및 회원프로필보기 구현
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelService.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/resources/static/images/image.png
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
Labels: duplicate, enhancement

#156 회원가입 체크조건 완료
  EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
Labels: documentation

#157 신고 작성,상세 기능추가 및 회원 차단 준비중
  EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/ReportController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/ReportDto.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/admin/mypage.jsp
  EveryFit/src/main/webapp/WEB-INF/views/admin/reportList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/report/apply.jsp
  EveryFit/src/main/webapp/WEB-INF/views/report/detail.jsp
Labels: enhancement

#158 프리미엄 결제 페이지 디자인, 마이페이지에 프리미엄 뱃지달기
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/MemberInterceptor.java
  EveryFit/src/main/resources/static/images/mypagememberCard.PNG
  EveryFit/src/main/webapp/WEB-INF/views/error/AuthorityException.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: enhancement

#159 정기결제시 모임장으로 이용하고 있는 모임 내역만 뜨도록 dao (moimListByEmailAndCrown) 생성
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/resources/static/images/mypagememberCardBefore.PNG
  EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
Labels: enhancement

#160 관리자 날짜 검색기능 오류 수정 및 신고목록 검색 수정
  EveryFit/src/main/java/com/kh/EveryFit/vo/AdminReportSearchVO.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/admin/jungmoList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/admin/memberList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/admin/moimList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/admin/reportList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/report/apply.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation

#161 마이페이지에서 비동기로 나의 모임 내역 가져오기
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/moimListForMyPageVO.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
Labels: enhancement

#162 헤더 신고하기 기능 추가, 메인페이지 글자수 제한 표시 기능 추가
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/report/apply.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation, duplicate, enhancement

#163 신고기능 사진 전송기능 구현
  EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/ReportController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/ReportAttachRestController.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/report/apply.jsp
  EveryFit/src/main/webapp/WEB-INF/views/report/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation, duplicate, enhancement

#164 관리자 버튼으로 회원 차단 기능 구현
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MemberDto.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/AdminOwnerInterceptor.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/admin/mypage.jsp
Labels: documentation, duplicate, enhancement

#165 리그 등록, 수정, 목록, 참가요강 화면 및 인풋 조건
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueEdit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueInsert.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: enhancement

#167 모임 등록 / 상세 페이지 디자인 구현 중
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MoimMemberDto.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/MoimMemberStatusVO.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/resources/static/images/add-jungmo-image.png
  EveryFit/src/main/resources/static/images/add-moim-image.png
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
Labels: duplicate, enhancement

#168 회원 구현중
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MemberRestController.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/member-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/member/changePw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/memberChangePw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: documentation

#169 스케줄러로 정기결제시 moim 테이블의 endtime도 정기결제된날짜+1달로 업데이트되도록 구현
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MoimDto.java
  EveryFit/src/main/java/com/kh/EveryFit/service/PaymentScheduler.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
Labels: enhancement

#172 Junhee
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: enhancement

#174 신고하기 기능 팝업으로 변경
  EveryFit/src/main/webapp/WEB-INF/views/report/apply.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation

#175 카카오페이 정기결제에 대한 기능들 구현
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/service/DownGradeMoimScheduler.java
  EveryFit/src/main/java/com/kh/EveryFit/service/PaymentScheduler.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/resources/static/images/mymoimExampleAfter.PNG
  EveryFit/src/main/resources/static/images/mymoimExampleBefore.PNG
  EveryFit/src/main/resources/static/images/mypagememberExampleAfter.PNG
  EveryFit/src/main/resources/static/images/mypagememberExampleBefore.PNG
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
Labels: enhancement

#177 보안 관련 작업중
  EveryFit/pom.xml
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimBoardDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/security/CustomSessionExpiredStrategy.java
  EveryFit/src/main/java/com/kh/EveryFit/security/CustomUserDetails.java
  EveryFit/src/main/java/com/kh/EveryFit/security/SecurityConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/security/SessionConfig.java
  EveryFit/src/main/resources/mybatis/moimBoard-mapper.xml
  EveryFit/src/main/resources/xml/Web.xml
  EveryFit/src/main/resources/xml/security-context.xml
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation, enhancement

#178 Junhee
  EveryFit/src/main/java/com/kh/EveryFit/component/LeagueMatchCalculater.java
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AttachDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AttachDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/LeagueRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueMatchRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/service/LeagueScheduler.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/LeagueScoreCalculateVO.java
  EveryFit/src/main/resources/mybatis/attach-mapper.xml
  EveryFit/src/main/resources/mybatis/league-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatch.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatchInsert.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamInsert.jsp
Labels: enhancement

#179 Junhee
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/MemberBlockInterceptor.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/LeagueListVO.java
  EveryFit/src/main/resources/mybatis/league-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/error/AdminException.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueEdit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueInsert.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatch.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamInsert.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/exit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPwFinish.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/joinFinish.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: enhancement

#180 다크모드,비밀번호변경,피드백
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MemberDto.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/AdminOwnerInterceptor.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/MemberBlockInterceptor.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/MemberInterceptor.java
  EveryFit/src/main/java/com/kh/EveryFit/service/EmailServiceImpl.java
  EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/changePw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/exit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPwFinish.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/joinFinish.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/memberChangePw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
Labels: documentation

#182 헤더, 관리자 헤더 디자인 수정
  EveryFit/src/main/resources/static/images/mainLogo.png
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation, enhancement

#183 홈페이지에서 검색기능 구현 (디자인X)
  EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/homeMoimSerach.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation, duplicate, enhancement

#184 신고하기 회원 정보 삽입, 풋터 위치 수정
  EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/ReportController.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/ReportDto.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/AdminReportSearchVO.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/admin/reportList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/homeMoimSerach.jsp
  EveryFit/src/main/webapp/WEB-INF/views/report/apply.jsp
  EveryFit/src/main/webapp/WEB-INF/views/report/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation, duplicate, enhancement

#185 채팅방입장, 리그정보없을때 등 자잘한 것들
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/ChatDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/ChatDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/ChatEntryDto.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/LeagueRestController.java
  EveryFit/src/main/resources/mybatis/chat-mapper.xml
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatch.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp
Labels: enhancement

#186 임시 저장
  EveryFit/pom.xml
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/ReportController.java
  EveryFit/src/main/java/com/kh/EveryFit/security/CustomSessionExpiredStrategy.java
  EveryFit/src/main/java/com/kh/EveryFit/security/CustomUserDetails.java
  EveryFit/src/main/java/com/kh/EveryFit/security/SecurityConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/security/SessionConfig.java
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Footer.jsp
Labels: documentation, duplicate

#187 모임, 웹소켓 수정 중
  EveryFit/pom.xml
  EveryFit/src/main/java/com/kh/EveryFit/configuration/WebsocketServerConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/ChatDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/ChatDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MoimDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelService.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/ChatRoomVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/MoimMemberStatusVO.java
  EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java
  EveryFit/src/main/resources/mybatis/chat-mapper.xml
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
Labels: bug, enhancement

#189 항소기능 구현 완료
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/AppealController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AppealDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AppealDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/AppealDto.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/AdminAppealSearchVO.java
  EveryFit/src/main/resources/mybatis/appeal-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/appeal/add.jsp
  EveryFit/src/main/webapp/WEB-INF/views/appeal/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/appeal/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/error/MemberBlockException.jsp
  EveryFit/src/main/webapp/WEB-INF/views/report/reportList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation, duplicate, enhancement

#192 비밀번호 표시,이메일축하메시지
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/configuration/KaKaoLoginConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MemberRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/service/EmailService.java
  EveryFit/src/main/java/com/kh/EveryFit/service/EmailServiceImpl.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/member-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/changePw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/memberChangePw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: documentation

#196 비밀번호 변경중
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/resources/mybatis/member-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/member/changePw.jsp
Labels: documentation

#197 홈페이지 내가 가입한 목록 추가
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/admin/mypage.jsp
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
Labels: documentation, duplicate

#199 회원 로그인시 회원가입 페이지 숨김처리
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation, duplicate, enhancement

#201 내가 찜한 목록 구현중
  EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AdminDaoImpl.java
  EveryFit/src/main/resources/mybatis/admin-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
Labels: documentation, duplicate

#202 나의결제리스트 디자인 수정
  EveryFit/src/main/webapp/WEB-INF/views/pay/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/premium.jsp
Labels: enhancement

#203 비밀번호찾기 구현중
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/resources/mybatis/member-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: documentation

#204 채팅 수정(회원이 계속 추가되는 오류)
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelService.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/ChatListVO.java
  EveryFit/src/main/java/com/kh/EveryFit/vo/ChatRoomVO.java
  EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java
  EveryFit/src/main/resources/mybatis/chat-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
Labels: duplicate, enhancement

#205 Junhee
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/LeagueRestController.java
  EveryFit/src/main/resources/mybatis/league-mapper.xml
  EveryFit/src/main/resources/mybatis/member-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamInsert.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
Labels: bug, enhancement

#207 모임, 채팅 인터셉터 구현 중
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/MoimMemberInterceptor.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/WebSocketServerInterceptor.java
  EveryFit/src/main/resources/mybatis/moim-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/error/AuthorityException.jsp
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/photoList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
Labels: enhancement

#209 Minha
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
Labels: documentation, duplicate, enhancement

#210 게시판 에니매이션 보여주기 추가
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/webapp/WEB-INF/views/faq/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/photoList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/Header.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
Labels: documentation

#212 모임 멤버 인터셉터 구현
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/MoimMemberInterceptor.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/resources/static/images/user.png
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
Labels: duplicate, enhancement

#213 배포 경로 일부 수정
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/webapp/WEB-INF/views/error/MemberBlockException.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/change.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/boardTable.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/edit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/product/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/report/detail.jsp
Labels: documentation

#214 모임멤버 인터셉터 - 관리자 제외 추가
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/MoimMemberInterceptor.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java
  EveryFit/src/main/resources/mybatis/chat-mapper.xml
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
Labels: duplicate

#215 수정코드
  EveryFit/src/main/java/com/kh/EveryFit/component/LeagueMatchCalculater.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/LeagueRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueMatchRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/service/LeagueScheduler.java
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatch.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamDetail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamInsert.jsp
  EveryFit/src/test/java/com/kh/EveryFit/Test01.java
Labels: documentation

#218 마지막
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDao.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dto/MemberDto.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/changePw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/exit.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPwFinish.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/memberChangePw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: documentation

#219 모든 로그 제거
  EveryFit/src/main/java/com/kh/EveryFit/configuration/InterceptorConfiguration.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/AdminController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/AppealController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/FaqController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/FreeBoardController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/HomeController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/KakaoPayController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/LeagueController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MemberController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimBoradController.java
  EveryFit/src/main/java/com/kh/EveryFit/controller/MoimController.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/AppealDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/LeagueDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/dao/MemberDaoImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/error/ExceptionControllerAdvice.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/MemberBlockInterceptor.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/MemberInterceptor.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/MoimMemberInterceptor.java
  EveryFit/src/main/java/com/kh/EveryFit/interceptor/WebSocketServerInterceptor.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/AttachRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/FAQAttachRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/LeagueRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MemberRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimBoardAttachRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/MoimRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/rest/ReportAttachRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/FreeBoardRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/InfoRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/restcontroller/LeagueMatchRestController.java
  EveryFit/src/main/java/com/kh/EveryFit/service/ChannelServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/service/DownGradeMoimScheduler.java
  EveryFit/src/main/java/com/kh/EveryFit/service/EmailServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/service/KakaoPayServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/service/LeagueScheduler.java
  EveryFit/src/main/java/com/kh/EveryFit/service/MoimServiceImpl.java
  EveryFit/src/main/java/com/kh/EveryFit/service/PaymentScheduler.java
  EveryFit/src/main/java/com/kh/EveryFit/websocket/ChatWebsocketServer.java
  EveryFit/src/main/resources/application.properties
  EveryFit/src/main/webapp/META-INF/maven/com.kh/EveryFit/pom.properties
  EveryFit/src/main/webapp/WEB-INF/views/admin/mypage.jsp
  EveryFit/src/main/webapp/WEB-INF/views/freeBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/home.jsp
  EveryFit/src/main/webapp/WEB-INF/views/homeMoimSerach.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueGuide.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueList.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueMatch.jsp
  EveryFit/src/main/webapp/WEB-INF/views/league/leagueTeamInsert.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/changePw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/findPw.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/login.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/create.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moim/jungmoCreate.jsp
  EveryFit/src/main/webapp/WEB-INF/views/moimBoard/detail.jsp
  EveryFit/src/main/webapp/WEB-INF/views/pay/list.jsp
  EveryFit/src/main/webapp/WEB-INF/views/template/adminHeader.jsp
  EveryFit/src/main/webapp/WEB-INF/views/ws/default.jsp
Labels: bug

#220 로그제거 2차
  EveryFit/src/main/webapp/WEB-INF/views/member/join.jsp
  EveryFit/src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: bug, documentation
